Minor change
TMDAD-Chat/file-api pull request #4
Opened 2022-04-15 19:53 UTC by FreddyMartinez

updating properties
updating controller response

2022-04-17 07:47 UTC, lAngelP requested changes

2022-04-17 07:47 UTC, lAngelP commented on src/main/java/com/example/fileapi/controller/FileController.java
> +        return ResponseEntity.status(HttpStatus.OK).body(name);
Si devuelves el string Spring pondrá el HTTP code 200, evitándote el trabajo a ti

2022-04-17 15:34 UTC, FreddyMartinez commented on src/main/java/com/example/fileapi/controller/FileController.java
> +        return ResponseEntity.status(HttpStatus.OK).body(name);
vale, lo cambié haciendo pruebas con el circuit breaker que siempre se me iba por el error, quité el decorador de Cors y se me quedó esto, lo devuelvo :wink:

2022-04-18 09:11 UTC, lAngelP approved these changes

2022-04-20 14:25 UTC, merged